name: SetMyHealth
main: me.Dankrushen.SetMyHealth.setMyHealth
version: 0.13
description: Allows you to easily alter players health, air, and hunger
author: Dankrushen
commands:
  sethealth:
    description: Sets a players health
    usage: /sethealth [player] <amount>
    aliases: sh
  sethunger:
    description: Sets a players hunger
    usage: /sethunger [player] <amount>
    aliases: shr
  setair:
    description: Sets a players air
    usage: /setair [player] <amount>
    aliases: sa
  maxhealth:
    description: Sets a players max health
    usage: /maxhealth [player] <amount>
    aliases: mh
  maxair:
    description: Sets a players max air
    usage: /maxair [player] <amount>
    aliases: ma
  setmyhealth:
    description: Gives plugin information
    usage: /setmyhealth
    aliases: smh